// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package db

import (
	"context"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (
  comment,
  post_id,
  user_id
) VALUES (
  $1, $2, $3
) RETURNING id, comment, post_id, user_id
`

type CreateCommentParams struct {
	Comment string `json:"comment"`
	PostID  int64  `json:"post_id"`
	UserID  int64  `json:"user_id"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment, arg.Comment, arg.PostID, arg.UserID)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.Comment,
		&i.PostID,
		&i.UserID,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments
WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteComment, id)
	return err
}

const editComment = `-- name: EditComment :one
UPDATE comments
SET comment = $2
WHERE id = $1
RETURNING id, comment, post_id, user_id
`

type EditCommentParams struct {
	ID      int64  `json:"id"`
	Comment string `json:"comment"`
}

func (q *Queries) EditComment(ctx context.Context, arg EditCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, editComment, arg.ID, arg.Comment)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.Comment,
		&i.PostID,
		&i.UserID,
	)
	return i, err
}

const listCommentsByPost = `-- name: ListCommentsByPost :many
SELECT
    c.id,
    c.comment,
    c.post_id,
    c.user_id,
    cu.username   AS commenter_username,
    p.title       AS post_title,
    p.description AS post_description,
    p.user_id     AS post_author_id,
    pu.username   AS post_author_username,
    cat.id        AS category_id,
    cat.name      AS category_name
FROM comments c
    JOIN posts p       ON p.id = c.post_id
    JOIN users cu      ON cu.id = c.user_id     -- comment author
    JOIN users pu      ON pu.id = p.user_id     -- post author
    JOIN categories cat ON cat.id = p.category_id
WHERE c.post_id = $1
ORDER BY c.id
`

type ListCommentsByPostRow struct {
	ID                 int64  `json:"id"`
	Comment            string `json:"comment"`
	PostID             int64  `json:"post_id"`
	UserID             int64  `json:"user_id"`
	CommenterUsername  string `json:"commenter_username"`
	PostTitle          string `json:"post_title"`
	PostDescription    string `json:"post_description"`
	PostAuthorID       int64  `json:"post_author_id"`
	PostAuthorUsername string `json:"post_author_username"`
	CategoryID         int64  `json:"category_id"`
	CategoryName       string `json:"category_name"`
}

func (q *Queries) ListCommentsByPost(ctx context.Context, postID int64) ([]ListCommentsByPostRow, error) {
	rows, err := q.db.Query(ctx, listCommentsByPost, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsByPostRow{}
	for rows.Next() {
		var i ListCommentsByPostRow
		if err := rows.Scan(
			&i.ID,
			&i.Comment,
			&i.PostID,
			&i.UserID,
			&i.CommenterUsername,
			&i.PostTitle,
			&i.PostDescription,
			&i.PostAuthorID,
			&i.PostAuthorUsername,
			&i.CategoryID,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
