// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package db

import (
	"context"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (
  comment,
  post_id,
  user_id
) VALUES (
  $1, $2, $3
) RETURNING id, comment, post_id, user_id
`

type CreateCommentParams struct {
	Comment string `json:"comment"`
	PostID  int64  `json:"post_id"`
	UserID  int64  `json:"user_id"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment, arg.Comment, arg.PostID, arg.UserID)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.Comment,
		&i.PostID,
		&i.UserID,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments
WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteComment, id)
	return err
}

const editComment = `-- name: EditComment :one
UPDATE comments
SET comment = $2
WHERE id = $1
RETURNING id, comment, post_id, user_id
`

type EditCommentParams struct {
	ID      int64  `json:"id"`
	Comment string `json:"comment"`
}

func (q *Queries) EditComment(ctx context.Context, arg EditCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, editComment, arg.ID, arg.Comment)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.Comment,
		&i.PostID,
		&i.UserID,
	)
	return i, err
}

const listCommentsByPost = `-- name: ListCommentsByPost :many
SELECT id, comment, post_id, user_id FROM comments
WHERE post_id = $1
`

func (q *Queries) ListCommentsByPost(ctx context.Context, postID int64) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listCommentsByPost, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.Comment,
			&i.PostID,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
