// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Category struct {
	ID       int32  `json:"id"`
	Category string `json:"category"`
}

type Comment struct {
	ID      int32  `json:"id"`
	Comment string `json:"comment"`
	PostID  *int32 `json:"post_id"`
	Author  string `json:"author"`
}

type Post struct {
	ID          int32  `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Author      string `json:"author"`
	CategoryID  int32  `json:"category_id"`
}
